module.exports = {
  dvd: [
    { id: 'action-movie', value: 0, name: 'Action' },
    { id: 'adventure-movie ', value: 0, name: 'Adventure' },
    { id: 'animation-movie', value: 0, name: 'Animation' },
    { id: 'comedy-movie', value: 0, name: 'Comedy' },
    { id: 'crime-movie', value: 0, name: 'Crime' },
    { id: 'documentary-movie', value: 0, name: 'Documentary' },
    { id: 'drama-movie', value: 0, name: 'Drama' },
    { id: 'family-movie ', value: 0, name: 'Family' },
    { id: 'fantasy-movie', value: 0, name: 'Fantasy' },
    { id: 'history-movie', value: 0, name: 'History' },
    { id: 'horror-movie', value: 0, name: 'Horror' },
    { id: 'music-movie', value: 0, name: 'Music' },
    { id: 'mystery-movie', value: 0, name: 'Mystery' },
    { id: 'romance-movie', value: 0, name: 'Romance' },
    { id: 'science-fiction-movie', value: 0, name: 'Science Fiction' },
    { id: 'thriller-movie', value: 0, name: 'Thriller' },
    { id: 'war-movie', value: 0, name: 'War' },
    { id: 'western-movie', value: 0, name: 'Western' },
  ],
  books: [
    { id: 'arts-photography-books', value: 0, name: 'Arts & Photography' },
    { id: 'biographies-memoirs-books', value: 0, name: 'Biography & Memoir' },
    { id: 'business-money-books', value: 0, name: 'Business & Money' },
    { id: "children's-books", value: 0, name: "Children's" },
    {
      id: 'cookbooks-food-drink-books',
      value: 0,
      name: 'Cooking, Food & Drink',
    },
    {
      id: 'health-fitness-diet-books',
      value: 0,
      name: 'Health, Fitness & Diet',
    },
    { id: 'history-books', value: 0, name: 'History' },
    { id: 'crafts-hobbies-home-books', value: 0, name: 'Hobbies & Crafts' },
    { id: 'homes-gardens-books', value: 0, name: 'Homes & Gardens' },
    {
      id: 'humour-entertainment-books',
      value: 0,
      name: 'Humour & Entertainment',
    },
    {
      id: 'mystery-thriller-suspense-books',
      value: 0,
      name: 'Mystery & Suspense',
    },
    {
      id: 'poetry-short-stories-books',
      value: 0,
      name: 'Poetry & Short Stories',
    },
    {
      id: 'politics-social-sciences-books',
      value: 0,
      name: 'Politics & Social Sciences',
    },
    { id: 'romance-books', value: 0, name: 'Romance' },
    {
      id: 'science-engineering-books',
      value: 0,
      name: 'Science & Engineering',
    },
    { id: 'science-fiction-fantasy-books', value: 0, name: 'Sci-Fi & Fantasy' },
    { id: 'self-development-books', value: 0, name: 'Self Development' },
    { id: 'spirituality-books', value: 0, name: 'Spirituality' },
    { id: 'sports-books', value: 0, name: 'Sports' },
    { id: 'technology-books', value: 0, name: 'Technology' },
    { id: 'travel-books', value: 0, name: 'Travel' },
    { id: 'true-crime-books', value: 0, name: 'True Crime' },
  ],
};
