module.exports = {
  dvd: [
    { id: 'action-movie', value:0, name: 'Action' },
    { id: 'adventure-movie ', value:0, name: 'Adventure' },
    { id: 'animation-movie', value:0, name: 'Animation' },
    { id: 'comedy-movie', value:0, name: 'Comedy' },
    { id: 'crime-movie', value:0, name: 'Crime' },
    { id: 'documentary-movie', value:0, name: 'Documentary' },
    { id: 'drama-movie', value:0, name: 'Drama' },
    { id: 'family-movie ', value:0, name: 'Family' },
    { id: 'fantasy-movie', value:0, name: 'Fantasy' },
    { id: 'history-movie', value:0, name: 'History' },
    { id: 'horror-movie', value:0, name: 'Horror' },
    { id: 'music-movie', value:0, name: 'Music' },
    { id: 'mystery-movie', value:0, name: 'Mystery' },
    { id: 'romance-movie', value:0, name: 'Romance' },
    { id: 'science-fiction-movie', value:0, name: 'Science Fiction' },
    { id: 'thriller-movie', value:0, name: 'Thriller' },
    { id: 'war-movie', value:0, name: 'War' },
    { id: 'western-movie', value:0, name: 'Western' },
  ],
  books: [
    { id: 'arts-photography-books', value: 0, name: 'Arts & Photography' },
    { id: 'biographies-memoirs-books', value: 0, name: 'Biographies & Memoirs' },
    { id: 'business-money-books', value: 0, name: 'Business & Money' },
    { id: "children's-books", value: 0, name: "Children's" },
    {
      id: 'cookbooks-food-drink-books',
      value: 0, name: 'Cookbooks, Food & Drink',
    },
    {
      id: 'crafts-hobbies-home-books',
      value: 0, name: 'Crafts, Hobbies & Home',
    },
    {
      id: 'health-fitness-diet-books',
      value: 0, name: 'Health, Fitness & Diet',
    },
    { id: 'history-books', value: 0, name: 'History' },
    {
      id: 'humour-entertainment-books',
      value: 0, name: 'Humour & Entertainment',
    },
    {
      id: 'mystery-thriller-suspense-books',
      value: 0, name: 'Mystery, Thriller & Suspense',
    },
    { id: 'poetry-short-story-books', value: 0, name: 'Poetry & Short Story' },
    {
      id: 'politics-social-science-books',
      value: 0, name: 'Politics & Social Science',
    },
    { id: 'romance-books', value: 0, name: 'Romance' },
    { id: 'science-math-books', value: 0, name: 'Science & Math' },
    { id: 'science-fiction-fantasy', value: 0, name: 'Science Fiction & Fantasy' },
    {
      id: 'self-help-spirituality-books',
      value: 0, name: 'Self-Help & Spirituality',
    },
    { id: 'sports-books', value: 0, name: 'Sports' },
    { id: 'technology-books', value: 0, name: 'Technology' },
    { id: 'travel-books', value: 0, name: 'Travel' },
  ],
};
